services:
  mongo:
    container_name: mongo
    image: mongo:5.0.25
    ports:
      - 27017:27017
    networks:
      - micro_svc
    volumes:
      - .data/mongo:/data/db

  mysql:
    container_name: mysql
    image: mysql:8.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - micro_svc

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: mysql
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - .data/realms/:/opt/keycloak/data/import/
    depends_on:
      - mysql
    networks:
      - micro_svc

networks:
  micro_svc:
    driver: bridge